# 01 - Data Cleaning

## Objective

Prepare the raw Semex/Lactanet dataset for downstream genomic analyses.

---

### Input

Master_Database_Consolidated_Final.xlsx

### Output

A clean and reproducible dataframe ready for analysis.

---

### Questions

- Are the variables correctly imported?
- Are dates properly formatted?
- Are numeric variables recognized correctly?
- Are there duplicated records?
- Are missing values identified?

In [9]:
# ============================================================
# IMPORT REQUIRED LIBRARIES
# ============================================================

import pandas as pd
import numpy as np

In [10]:
# ============================================================
# LOAD THE DATASET
# ============================================================

file_path = "../Master_Database_Consolidated_Final.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [11]:
# ============================================================
# BASIC INFORMATION
#how many lines and columns my file has
# ============================================================

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 668
Columns: 168

In [12]:
# ============================================================
# DISPLAY THE FIRST ROWS
#Verify that the correct dataset was loaded
# ============================================================

df.head()

,Barn ID,Barn Name,Ear Tag Code,Registration Number,Registration Name,Chain Number,Location Pen Number,Nomination ID,Order Number,Order Date,...,Barn Name_Milk Proteins,Ear Tag Code_Milk Proteins,Registration Name_Milk Proteins,Birth Date_Milk Proteins,A2A2_Milk Proteins,KappaBB_Milk Proteins,BetaCasein_Milk Proteins,Lactoglobulin_Milk Proteins,year,RP
0,2528,RAISAVIEW AMBROSE PURDY,CA000014992416,CA000014992416,RAISAVIEW BULLSEYE PURDY,NaN,9.0,HOCAN14992416,13115-00-240718,2024-07-19 06:20:07,...,RAISAVIEW AMBROSE PURDY,CA000014992416,RAISAVIEW BULLSEYE PURDY,2024-07-17,A1/A2,AB,AA,AB,2024,0
1,2530,RAISAVIEW A ISLAND APPLE,CA000014992418,CA000014992418,RAISAVIEW A ISLAND APPLE,NaN,9.0,HOCAN14992418,13115-00-240724,2024-07-25 12:50:04,...,RAISAVIEW A ISLAND APPLE,CA000014992418,RAISAVIEW A ISLAND APPLE,2024-07-22,A2/A2,BB,AA,AA,2024,0
2,2531,RAISAVIEW A CHERRY APPLE,CA000014992419,CA000014992419,RAISAVIEW A CHERRY APPLE,NaN,9.0,HOCAN14992419,13115-00-240724,2024-07-25 12:50:04,...,RAISAVIEW A CHERRY APPLE,CA000014992419,RAISAVIEW A CHERRY APPLE,2024-07-22,A1/A2,BB,AA,AB,2024,0
3,2532,RAISAVIEW AMBROSE CROWN,CA000014992420,CA000014992420,RAISAVIEW BULLSEYE PRUDENCE,NaN,9.0,HOCAN14992420,13115-00-240724,2024-07-25 12:50:04,...,RAISAVIEW AMBROSE CROWN,CA000014992420,RAISAVIEW BULLSEYE PRUDENCE,2024-07-23,A2/A2,AB,AA,BB,2024,0
4,2533,RAISAVIEW D CORNER APPLE,CA000014992421,CA000014992421,RAISAVIEW D CORNER APPLE,NaN,9.0,HOCAN14992421,13115-00-240724,2024-07-25 12:50:04,...,RAISAVIEW D CORNER APPLE,CA000014992421,RAISAVIEW D CORNER APPLE,2024-07-23,A2/A2,AB,AA,AB,2024,0

In [13]:
# ============================================================
# DATASET AUDIT
# Understanding the structure before cleaning
# ============================================================

print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nData types:")
display(df.dtypes)

print("\nMissing values:")
display(df.isna().sum().sort_values(ascending=False).head(20))
df.isna().sum()

============================================================
DATASET OVERVIEW
============================================================
Rows: 668
Columns: 168

Data types:

Barn ID                        int64
Barn Name                        str
Ear Tag Code                     str
Registration Number              str
Registration Name                str
                               ...
KappaBB_Milk Proteins            str
BetaCasein_Milk Proteins         str
Lactoglobulin_Milk Proteins      str
year                           int64
RP                             int64
Length: 168, dtype: object

Missing values:

Chain Number                 668
Original Dam Reg Number      668
Original MGS Reg Number      559
Original MGS Semen Code      559
Original MGS Name            559
Original Sire Reg Number     556
Original Sire Semen Code     556
Original Sire Name           556
Birth Date_BvdTest           509
Barn Name_BvdTest            509
Ear Tag Code_BvdTest         509
Barn ID_BvdTest              509
Bvd Test_BvdTest             509
Registration Name_BvdTest    509
Polled Test                  483
Color Test                   483
Current group                388
Initial group                388
Calving Date                 325
Due Date                     264
dtype: int64

Barn ID                          0
Barn Name                        1
Ear Tag Code                     0
Registration Number              0
Registration Name               13
                              ...
KappaBB_Milk Proteins          170
BetaCasein_Milk Proteins       170
Lactoglobulin_Milk Proteins    170
year                             0
RP                               0
Length: 168, dtype: int64

In [14]:
# ============================================================
# COLUMN NAMES
# ============================================================

print(df.columns.tolist())

['Barn ID', 'Barn Name', 'Ear Tag Code', 'Registration Number', 'Registration Name', 'Chain Number', 'Location Pen Number', 'Nomination ID', 'Order Number', 'Order Date', 'Lab Status', 'Lab Status Date', 'Genotyped', 'Current group', 'Initial group', 'Birth Date', 'Due Date', 'Calving Date', 'Type', 'Lact. Number', 'Preg Status', 'No. Services', 'Inb.%', 'Genomic Inb. %', 'R-Value', 'Sire Semen Code', 'Sire Reg Number', 'Sire Name', 'Dam', 'MGS Semen Code', 'MGS Reg Number', 'MGS Name', 'GMGS Semen Code', 'GMGS Reg Number', 'GMGS Name', 'Proof Source', 'Evaluation date', 'Immunity', 'Calf', 'LPI', 'paLPI', 'Pro$', 'paPro$', 'Client Index', 'paClient Index', 'PROD', 'HEALTH', 'L-TYPE', 'REPRO', 'M-ABILITY', 'ENVIRO', 'Milk (kg)', 'Fat (kg)', '%Fat', 'Prot (kg)', '%Prot', 'FE', 'BMR', 'ME', 'SCS', 'HL', 'MR', 'MDR', 'HH', 'LP', 'DF', 'MSp', 'MTemp', 'CA', 'DCA', 'BCS', 'CO', 'CH', 'Conf', 'MS', 'FL', 'DS', 'RU', 'UD', 'UT', 'MSu', 'UF', 'FA', 'TL', 'FTP', 'RTP', 'RAH', 'RAW', 'FAng', 'HD', 'LOC', 'FLV', 'RLSV', 'RLRV', 'BQ', 'STA', 'HFE', 'CW', 'BD', 'RS', 'RAng', 'PW', 'LS', 'TP', 'Polled Test', 'Color Test', 'BLAD', 'BY', 'CIT', 'CVM', 'DUMPS', 'MF', 'HH1', 'HH2', 'HH3', 'HH4', 'HH5', 'HH6', 'HCD', 'HMW', 'A2 Test', 'KappaBB', 'Lactoglobulin', 'BetaCasein', 'AY%', 'BS%', 'GU%', 'HO%', 'JE%', 'Parent conflict', 'Parent discovered', 'Original Sire Semen Code', 'Original Sire Reg Number', 'Original Sire Name', 'Original Dam Reg Number', 'Original MGS Semen Code', 'Original MGS Reg Number', 'Original MGS Name', 'Barn ID_Immunity', 'Barn Name_Immunity', 'Ear Tag Code_Immunity', 'Registration Name_Immunity', 'Birth Date_Immunity', 'Immunity_Immunity', 'Calf_Immunity', 'Barn ID_BvdTest', 'Barn Name_BvdTest', 'Ear Tag Code_BvdTest', 'Registration Name_BvdTest', 'Birth Date_BvdTest', 'Bvd Test_BvdTest', 'Barn ID_A2 Test', 'Barn Name_A2 Test', 'Ear Tag Code_A2 Test', 'Registration Name_A2 Test', 'Birth Date_A2 Test', 'A2 Test_A2 Test', 'Barn ID_Milk Proteins', 'Barn Name_Milk Proteins', 'Ear Tag Code_Milk Proteins', 'Registration Name_Milk Proteins', 'Birth Date_Milk Proteins', 'A2A2_Milk Proteins', 'KappaBB_Milk Proteins', 'BetaCasein_Milk Proteins', 'Lactoglobulin_Milk Proteins', 'year', 'RP']

In [15]:
# ============================================================
# DUPLICATED ROWS
# ============================================================

print(f"Duplicated rows: {df.duplicated().sum()}")

Duplicated rows: 0

In [16]:
# ============================================================
# DATASET DIMENSIONS
# How large is our dataset?
# ============================================================

print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Number of rows: 668
Number of columns: 168

In [17]:
# ============================================================
# DATA TYPES
# Did pandas correctly identify each variable?
# ============================================================

display(df.dtypes)

Barn ID                        int64
Barn Name                        str
Ear Tag Code                     str
Registration Number              str
Registration Name                str
                               ...
KappaBB_Milk Proteins            str
BetaCasein_Milk Proteins         str
Lactoglobulin_Milk Proteins      str
year                           int64
RP                             int64
Length: 168, dtype: object

In [18]:
# ============================================================
# MISSING VALUES
# Which variables contain missing information?
# ============================================================

missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

display(missing)

Chain Number               668
Original Dam Reg Number    668
Original MGS Reg Number    559
Original MGS Semen Code    559
Original MGS Name          559
                          ...
HH4                          0
HCD                          0
HMW                          0
year                         0
RP                           0
Length: 168, dtype: int64

In [19]:
# ============================================================
# DUPLICATED ROWS
# ============================================================

duplicates = df.duplicated().sum()

print(f"Duplicated rows: {duplicates}")

Duplicated rows: 0

In [20]:
# ============================================================
# COLUMN NAMES
# ============================================================

for column in df.columns:
    print(column)

Barn ID
Barn Name
Ear Tag Code
Registration Number
Registration Name
Chain Number
Location Pen Number
Nomination ID
Order Number
Order Date
Lab Status
Lab Status Date
Genotyped
Current group
Initial group
Birth Date
Due Date
Calving Date
Type
Lact. Number
Preg Status
No. Services
Inb.%
Genomic Inb. %
R-Value
Sire Semen Code
Sire Reg Number
Sire Name
Dam
MGS Semen Code
MGS Reg Number
MGS Name
GMGS Semen Code
GMGS Reg Number
GMGS Name
Proof Source
Evaluation date
Immunity
Calf
LPI
paLPI
Pro$
paPro$
Client Index
paClient Index
PROD
HEALTH
L-TYPE
REPRO
M-ABILITY
ENVIRO
Milk (kg)
Fat (kg)
%Fat
Prot (kg)
%Prot
FE
BMR
ME
SCS
HL
MR
MDR
HH
LP
DF
MSp
MTemp
CA
DCA
BCS
CO
CH
Conf
MS
FL
DS
RU
UD
UT
MSu
UF
FA
TL
FTP
RTP
RAH
RAW
FAng
HD
LOC
FLV
RLSV
RLRV
BQ
STA
HFE
CW
BD
RS
RAng
PW
LS
TP
Polled Test
Color Test
BLAD
BY
CIT
CVM
DUMPS
MF
HH1
HH2
HH3
HH4
HH5
HH6
HCD
HMW
A2 Test
KappaBB
Lactoglobulin
BetaCasein
AY%
BS%
GU%
HO%
JE%
Parent conflict
Parent discovered
Original Sire Semen Code
Original Sire Reg Number
Original Sire Name
Original Dam Reg Number
Original MGS Semen Code
Original MGS Reg Number
Original MGS Name
Barn ID_Immunity
Barn Name_Immunity
Ear Tag Code_Immunity
Registration Name_Immunity
Birth Date_Immunity
Immunity_Immunity
Calf_Immunity
Barn ID_BvdTest
Barn Name_BvdTest
Ear Tag Code_BvdTest
Registration Name_BvdTest
Birth Date_BvdTest
Bvd Test_BvdTest
Barn ID_A2 Test
Barn Name_A2 Test
Ear Tag Code_A2 Test
Registration Name_A2 Test
Birth Date_A2 Test
A2 Test_A2 Test
Barn ID_Milk Proteins
Barn Name_Milk Proteins
Ear Tag Code_Milk Proteins
Registration Name_Milk Proteins
Birth Date_Milk Proteins
A2A2_Milk Proteins
KappaBB_Milk Proteins
BetaCasein_Milk Proteins
Lactoglobulin_Milk Proteins
year
RP

In [22]:
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

In [23]:
# ============================================================
# DATA QUALITY SUMMARY
# ============================================================

quality = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing (%)": round(df.isnull().mean()*100,2),
    "Data Type": df.dtypes
})

quality = quality.sort_values(
    by="Missing (%)",
    ascending=False
)

quality.head(25)

                           Missing Values  Missing (%)       Data Type
Chain Number                          668       100.00         float64
Original Dam Reg Number               668       100.00         float64
Original MGS Reg Number               559        83.68             str
Original MGS Semen Code               559        83.68             str
Original MGS Name                     559        83.68             str
Original Sire Reg Number              556        83.23             str
Original Sire Semen Code              556        83.23             str
Original Sire Name                    556        83.23             str
Birth Date_BvdTest                    509        76.20  datetime64[us]
Barn Name_BvdTest                     509        76.20             str
Ear Tag Code_BvdTest                  509        76.20             str
Barn ID_BvdTest                       509        76.20         float64
Bvd Test_BvdTest                      509        76.20             str
Registration Name_BvdTest             509        76.20             str
Polled Test                           483        72.31             str
Color Test                            483        72.31             str
Current group                         388        58.08             str
Initial group                         388        58.08             str
Calving Date                          325        48.65  datetime64[us]
Due Date                              264        39.52  datetime64[us]
No. Services                          202        30.24         float64
HO%                                   179        26.80         float64
JE%                                   179        26.80         float64
AY%                                   179        26.80         float64
GU%                                   179        26.80         float64

In [24]:
# ============================================================
# GENOMIC VARIABLES
# ============================================================

genomic_columns = [
    col
    for col in df.columns
    if any(word in col.upper() for word in
           ["MILK","FAT","PROT","LPI","PRO","HL","MS","FL","DS","RU","CONF"])
]

genomic_columns

['Proof Source',
 'LPI',
 'paLPI',
 'Pro$',
 'paPro$',
 'PROD',
 'REPRO',
 'Milk (kg)',
 'Fat (kg)',
 '%Fat',
 'Prot (kg)',
 '%Prot',
 'HL',
 'MSp',
 'Conf',
 'MS',
 'FL',
 'DS',
 'RU',
 'MSu',
 'FLV',
 'Parent conflict',
 'Barn ID_Milk Proteins',
 'Barn Name_Milk Proteins',
 'Ear Tag Code_Milk Proteins',
 'Registration Name_Milk Proteins',
 'Birth Date_Milk Proteins',
 'A2A2_Milk Proteins',
 'KappaBB_Milk Proteins',
 'BetaCasein_Milk Proteins',
 'Lactoglobulin_Milk Proteins']

In [25]:
# ============================================================
# DATA QUALITY SUMMARY
# ============================================================

quality = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing (%)": round(df.isnull().mean()*100,2),
    "Data Type": df.dtypes
})

quality = quality.sort_values(
    by="Missing (%)",
    ascending=False
)

quality.head(25)

                           Missing Values  Missing (%)       Data Type
Chain Number                          668       100.00         float64
Original Dam Reg Number               668       100.00         float64
Original MGS Reg Number               559        83.68             str
Original MGS Semen Code               559        83.68             str
Original MGS Name                     559        83.68             str
Original Sire Reg Number              556        83.23             str
Original Sire Semen Code              556        83.23             str
Original Sire Name                    556        83.23             str
Birth Date_BvdTest                    509        76.20  datetime64[us]
Barn Name_BvdTest                     509        76.20             str
Ear Tag Code_BvdTest                  509        76.20             str
Barn ID_BvdTest                       509        76.20         float64
Bvd Test_BvdTest                      509        76.20             str
Registration Name_BvdTest             509        76.20             str
Polled Test                           483        72.31             str
Color Test                            483        72.31             str
Current group                         388        58.08             str
Initial group                         388        58.08             str
Calving Date                          325        48.65  datetime64[us]
Due Date                              264        39.52  datetime64[us]
No. Services                          202        30.24         float64
HO%                                   179        26.80         float64
JE%                                   179        26.80         float64
AY%                                   179        26.80         float64
GU%                                   179        26.80         float64

In [26]:
# ============================================================
# VARIABLE TYPES
# ============================================================

df.dtypes.value_counts()

int64             66
str               55
float64           37
datetime64[us]    10
Name: count, dtype: int64

In [27]:
# ============================================================
# GENERAL INFORMATION
# ============================================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Columns: 168 entries, Barn ID to RP
dtypes: datetime64[us](10), float64(37), int64(66), str(55)
memory usage: 876.9 KB

In [28]:
# ============================================================
# CREATE A WORKING COPY
# Never modify the original dataset
# ============================================================

df_raw = df.copy()

print("Working copy created successfully.")

Working copy created successfully.

In [29]:
# ============================================================
# COLUMN CATEGORIES
# ============================================================

column_categories = {
    "Animal Information": [],
    "Pedigree": [],
    "Reproduction": [],
    "Genomic Evaluations": [],
    "Indexes": [],
    "Haplotypes": [],
    "Milk Proteins": [],
    "Inbreeding": [],
    "Administrative": [],
    "Other": []
}

In [30]:
# ============================================================
# EXPORT COLUMN NAMES
# ============================================================

columns = pd.DataFrame({
    "Variable": df.columns
})

columns

                        Variable
0                        Barn ID
1                      Barn Name
2                   Ear Tag Code
3            Registration Number
4              Registration Name
..                           ...
163        KappaBB_Milk Proteins
164     BetaCasein_Milk Proteins
165  Lactoglobulin_Milk Proteins
166                         year
167                           RP

[168 rows x 1 columns]

In [33]:
import os

print(os.getcwd())

c:\Users\arincon\OneDrive - SISTEMAS TECNICOS DE ENCOFRADOS S.A\DEBIDA DILIGENCIA\Documentos\Proyecto_Granja\notebooks

In [34]:
columns.to_excel("docs/Data_Dictionary.xlsx", index=False)

print("Data Dictionary saved successfully!")

Data Dictionary saved successfully!

In [35]:
# ============================================================
# SUMMARY OF THE DATASET
# ============================================================

display(df.describe())

,Barn ID,Chain Number,Location Pen Number,Order Date,Lab Status Date,Birth Date,Due Date,Calving Date,Lact. Number,No. Services,...,Immunity_Immunity,Calf_Immunity,Barn ID_BvdTest,Birth Date_BvdTest,Barn ID_A2 Test,Birth Date_A2 Test,Barn ID_Milk Proteins,Birth Date_Milk Proteins,year,RP
count,668.000000,0.0,574.000000,525,525,668,404,343,668.000000,466.000000,...,500.000000,500.00000,159.000000,159,498.000000,498,498.000000,498,668.000000,668.0
mean,6479.202096,NaN,7.996516,2024-10-05 23:43:16.563447,2024-11-13 17:12:27.314327,2023-11-23 07:30:32.335329,2026-12-11 22:59:24.356435,2025-12-22 18:19:56.501457,1.296407,2.293991,...,102.234000,104.66800,6142.867925,2025-11-15 17:57:44.150943,5425.042169,2024-07-31 01:06:30.361445,5425.042169,2024-07-31 01:06:30.361445,2023.387725,0.0
min,222.000000,NaN,1.000000,2022-02-28 11:25:06,2022-04-08 08:55:22.720000,2013-12-26 00:00:00,2026-06-08 00:00:00,2024-12-25 00:00:00,0.000000,1.000000,...,89.000000,91.00000,2581.000000,2025-06-02 00:00:00,222.000000,2021-04-08 00:00:00,222.000000,2021-04-08 00:00:00,2013.000000,0.0
25%,3159.000000,NaN,2.000000,2023-11-02 08:40:06,2023-12-23 09:55:14.655000,2022-09-12 12:00:00,2026-09-28 00:00:00,2025-09-23 12:00:00,0.000000,1.000000,...,99.000000,101.00000,3844.500000,2025-09-03 12:00:00,3494.000000,2023-09-18 06:00:00,3494.000000,2023-09-18 06:00:00,2022.000000,0.0
50%,3747.500000,NaN,8.000000,2024-11-13 10:20:04,2025-01-24 09:55:52.325000,2024-06-19 00:00:00,2026-12-14 00:00:00,2026-01-01 00:00:00,1.000000,2.000000,...,102.000000,105.00000,8446.000000,2025-11-06 00:00:00,3787.000000,2024-09-06 00:00:00,3787.000000,2024-09-06 00:00:00,2024.000000,0.0
75%,8355.250000,NaN,9.000000,2025-10-10 12:24:41,2025-11-16 05:00:45.923000,2025-07-28 06:00:00,2027-03-07 00:00:00,2026-04-02 12:00:00,2.000000,3.000000,...,106.000000,108.00000,8490.500000,2026-02-13 00:00:00,8371.750000,2025-08-11 00:00:00,8371.750000,2025-08-11 00:00:00,2025.000000,0.0
max,84691.000000,NaN,37.000000,2026-06-30 08:16:28.830000,2026-07-02 16:50:10.645000,2026-07-05 00:00:00,2027-04-13 00:00:00,2026-07-05 00:00:00,9.000000,9.000000,...,115.000000,118.00000,8540.000000,2026-04-20 00:00:00,84691.000000,2026-04-20 00:00:00,84691.000000,2026-04-20 00:00:00,2026.000000,0.0
std,11175.552225,NaN,8.682292,NaN,NaN,NaN,NaN,NaN,1.715662,1.399480,...,4.774603,4.96337,2554.223048,NaN,5604.336927,NaN,5604.336927,NaN,2.193277,0.0

In [36]:
# ============================================================
# SUMMARY OF CATEGORICAL VARIABLES
# ============================================================

display(df.describe(include="object"))

C:\Users\arincon\AppData\Local\Temp\ipykernel_15956\493126877.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include="object"))

,Barn Name,Ear Tag Code,Registration Number,Registration Name,Nomination ID,Order Number,Lab Status,Genotyped,Current group,Initial group,...,Ear Tag Code_A2 Test,Registration Name_A2 Test,A2 Test_A2 Test,Barn Name_Milk Proteins,Ear Tag Code_Milk Proteins,Registration Name_Milk Proteins,A2A2_Milk Proteins,KappaBB_Milk Proteins,BetaCasein_Milk Proteins,Lactoglobulin_Milk Proteins
count,667,668,668,655,528,525,525,668,280,280,...,498,498,498,498,498,498,498,498,498,498
unique,667,668,668,655,528,106,3,2,4,3,...,498,498,3,498,498,498,3,6,2,4
top,RAISAVIEW AMBROSE PURDY,CA000014992416,CA000014992416,RAISAVIEW BULLSEYE PURDY,HOCAN14992416,13115-SYS-260226,Completed,Y,Sexed,Sexed,...,CA000014992416,RAISAVIEW BULLSEYE PURDY,A2/A2,RAISAVIEW AMBROSE PURDY,CA000014992416,RAISAVIEW BULLSEYE PURDY,A2/A2,AB,AA,AB
freq,1,1,1,1,1,18,495,603,190,178,...,1,1,270,1,1,1,270,235,494,224

In [37]:
# ============================================================
# SAVE A CLEAN COPY OF THE ORIGINAL DATASET
# ============================================================

df_raw = df.copy()

print("Original dataset copied successfully.")

Original dataset copied successfully.

In [38]:
df.describe()

,Barn ID,Chain Number,Location Pen Number,Order Date,Lab Status Date,Birth Date,Due Date,Calving Date,Lact. Number,No. Services,...,Immunity_Immunity,Calf_Immunity,Barn ID_BvdTest,Birth Date_BvdTest,Barn ID_A2 Test,Birth Date_A2 Test,Barn ID_Milk Proteins,Birth Date_Milk Proteins,year,RP
count,668.000000,0.0,574.000000,525,525,668,404,343,668.000000,466.000000,...,500.000000,500.00000,159.000000,159,498.000000,498,498.000000,498,668.000000,668.0
mean,6479.202096,NaN,7.996516,2024-10-05 23:43:16.563447,2024-11-13 17:12:27.314327,2023-11-23 07:30:32.335329,2026-12-11 22:59:24.356435,2025-12-22 18:19:56.501457,1.296407,2.293991,...,102.234000,104.66800,6142.867925,2025-11-15 17:57:44.150943,5425.042169,2024-07-31 01:06:30.361445,5425.042169,2024-07-31 01:06:30.361445,2023.387725,0.0
min,222.000000,NaN,1.000000,2022-02-28 11:25:06,2022-04-08 08:55:22.720000,2013-12-26 00:00:00,2026-06-08 00:00:00,2024-12-25 00:00:00,0.000000,1.000000,...,89.000000,91.00000,2581.000000,2025-06-02 00:00:00,222.000000,2021-04-08 00:00:00,222.000000,2021-04-08 00:00:00,2013.000000,0.0
25%,3159.000000,NaN,2.000000,2023-11-02 08:40:06,2023-12-23 09:55:14.655000,2022-09-12 12:00:00,2026-09-28 00:00:00,2025-09-23 12:00:00,0.000000,1.000000,...,99.000000,101.00000,3844.500000,2025-09-03 12:00:00,3494.000000,2023-09-18 06:00:00,3494.000000,2023-09-18 06:00:00,2022.000000,0.0
50%,3747.500000,NaN,8.000000,2024-11-13 10:20:04,2025-01-24 09:55:52.325000,2024-06-19 00:00:00,2026-12-14 00:00:00,2026-01-01 00:00:00,1.000000,2.000000,...,102.000000,105.00000,8446.000000,2025-11-06 00:00:00,3787.000000,2024-09-06 00:00:00,3787.000000,2024-09-06 00:00:00,2024.000000,0.0
75%,8355.250000,NaN,9.000000,2025-10-10 12:24:41,2025-11-16 05:00:45.923000,2025-07-28 06:00:00,2027-03-07 00:00:00,2026-04-02 12:00:00,2.000000,3.000000,...,106.000000,108.00000,8490.500000,2026-02-13 00:00:00,8371.750000,2025-08-11 00:00:00,8371.750000,2025-08-11 00:00:00,2025.000000,0.0
max,84691.000000,NaN,37.000000,2026-06-30 08:16:28.830000,2026-07-02 16:50:10.645000,2026-07-05 00:00:00,2027-04-13 00:00:00,2026-07-05 00:00:00,9.000000,9.000000,...,115.000000,118.00000,8540.000000,2026-04-20 00:00:00,84691.000000,2026-04-20 00:00:00,84691.000000,2026-04-20 00:00:00,2026.000000,0.0
std,11175.552225,NaN,8.682292,NaN,NaN,NaN,NaN,NaN,1.715662,1.399480,...,4.774603,4.96337,2554.223048,NaN,5604.336927,NaN,5604.336927,NaN,2.193277,0.0

In [32]:
columns.to_excel("../docs/Data_Dictionary.xlsx", index=False)

OSError: Cannot save file into a non-existent directory: '..\docs'